### ISSUE TITLE
Deploy errors on GenerateFlowLink.cls

### ISSUE THREAD

**Issue by ericrsmith35** [alexed1/LightningFlowComponents#227]
Is something missing?  Here are the deploy errors:

force-app\main\default\classes\GenerateFlowLink.cls  Method does not exist or incorrect signature: void generateParam(String, String) from the type GenerateFlowLink (16:18)
force-app\main\default\classes\GenerateFlowLink.cls  Method does not exist or incorrect signature: void generateParam(String, String) from the type GenerateFlowLink (22:21)
force-app\main\default\classes\GenerateFlowLink.cls  Method does not exist or incorrect signature: void generateParam(String, String) from the type GenerateFlowLink (18:28)

**Comment by alexed1** [comment]
fixed this issue. also posted an unmanaged package to https://unofficialsf.com/generate-urls-that-launch-flows-with-generate-flow-link/

**Comment by ericrsmith35** [comment]
There is still an error when trying to install the unmanaged package.  I've tried Production, Developer and Sandbox.
![Capture](https://user-images.githubusercontent.com/24724447/71519425-7bbd8200-2885-11ea-9439-96c530e0e02b.PNG)

**Comment by alexed1** [comment]
try this one for navigate:
https://login.salesforce.com/packaging/installPackage.apexp?p0=04tf4000004PsKM&isdtp=p1

Alex Edelstein
Sr. Dir. Product Management - Automation and Decisioning
Salesforce

<http://smart.salesforce.com/sig/aedelstein//us_mb/default/link.html>

**Comment by ericrsmith35** [comment]
That works
